version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: